import {
  Square,
  Type,
  Heading as HeadingIcon,
  MousePointerClick,
  Image as ImageIcon,
  Link as LinkIcon,
  LayoutPanelTop,
  Minus,
  Columns2,
  CreditCard,
  FormInput,
  StretchVertical,
  Quote as QuoteIcon,
  TextCursorInput,
  LayoutGrid,
  Star,
  Heart,
  Check,
  ArrowRight,
  Sparkles,
  Zap,
  Shield,
  Globe,
  Mail,
  Play,
  Bell,
  Search,
  Boxes,
} from 'lucide-react';

/** Curated icon set available to the Icon widget. */
export const ICON_SET = { Star, Heart, Check, ArrowRight, Sparkles, Zap, Shield, Globe, Mail, Play, Bell, Search };

/**
 * Component registry for the flow builder. Each component renders a real HTML
 * tag with real CSS (kebab-case keys, with units). Elements can also be set to
 * position:absolute and freely moved/resized on the canvas.
 */
export const COMPONENTS = {
  Body: {
    label: 'Body',
    tag: 'div',
    container: true,
    icon: LayoutPanelTop,
    defaultStyle: {
      position: 'relative',
      display: 'flex',
      'flex-direction': 'column',
      'min-height': '100%',
      'background-color': '#ffffff',
      'font-family': 'system-ui, -apple-system, "Segoe UI", sans-serif',
    },
  },
  Section: {
    label: 'Section',
    tag: 'section',
    container: true,
    icon: LayoutPanelTop,
    defaultStyle: {
      display: 'flex',
      'flex-direction': 'column',
      'padding-top': '48px',
      'padding-bottom': '48px',
      'padding-left': '48px',
      'padding-right': '48px',
      gap: '16px',
    },
  },
  Box: {
    label: 'Box',
    tag: 'div',
    container: true,
    icon: Square,
    defaultStyle: { display: 'block', 'padding-top': '16px', 'padding-bottom': '16px', 'padding-left': '16px', 'padding-right': '16px' },
  },
  Grid: {
    label: 'Grid',
    tag: 'div',
    container: true,
    icon: LayoutGrid,
    defaultStyle: { display: 'grid', 'grid-template-columns': 'repeat(3, 1fr)', gap: '16px' },
  },
  Icon: {
    label: 'Icon',
    tag: 'span',
    container: false,
    icon: Star,
    defaultProps: { iconName: 'Star' },
    defaultStyle: { display: 'inline-flex', width: '40px', height: '40px', color: '#4f46e5' },
  },
  Columns: {
    label: 'Columns',
    tag: 'div',
    container: true,
    icon: Columns2,
    defaultStyle: { display: 'flex', 'flex-direction': 'row', gap: '16px', 'align-items': 'stretch' },
  },
  Card: {
    label: 'Card',
    tag: 'div',
    container: true,
    icon: CreditCard,
    defaultStyle: {
      display: 'flex',
      'flex-direction': 'column',
      gap: '10px',
      'padding-top': '20px',
      'padding-bottom': '20px',
      'padding-left': '20px',
      'padding-right': '20px',
      'background-color': '#ffffff',
      'border-radius': '14px',
      'box-shadow': '0 1px 2px rgba(0,0,0,0.06), 0 8px 24px rgba(0,0,0,0.08)',
    },
  },
  Heading: {
    label: 'Heading',
    tag: 'h2',
    container: false,
    icon: HeadingIcon,
    defaultProps: { text: 'Heading' },
    defaultStyle: { 'font-size': '32px', 'font-weight': '700', 'margin-top': '0px', 'margin-bottom': '0px', color: '#111827' },
  },
  Text: {
    label: 'Text',
    tag: 'p',
    container: false,
    icon: Type,
    defaultProps: { text: 'Some paragraph text.' },
    defaultStyle: { 'font-size': '16px', 'line-height': '1.5', 'margin-top': '0px', 'margin-bottom': '0px', color: '#374151' },
  },
  Quote: {
    label: 'Quote',
    tag: 'blockquote',
    container: false,
    icon: QuoteIcon,
    defaultProps: { text: 'A memorable quote goes here.' },
    defaultStyle: {
      'margin-top': '0px',
      'margin-bottom': '0px',
      'padding-left': '16px',
      'border-left-width': '3px',
      'border-left-style': 'solid',
      'border-color': '#4f46e5',
      'font-style': 'italic',
      'font-size': '18px',
      color: '#374151',
    },
  },
  Link: {
    label: 'Link',
    tag: 'a',
    container: false,
    icon: LinkIcon,
    defaultProps: { text: 'Link', href: '#' },
    defaultStyle: { color: '#4f46e5', 'text-decoration-line': 'underline' },
  },
  Button: {
    label: 'Button',
    tag: 'button',
    container: false,
    icon: MousePointerClick,
    defaultProps: { text: 'Button' },
    defaultStyle: {
      'background-color': '#4f46e5',
      color: '#ffffff',
      'padding-top': '10px',
      'padding-bottom': '10px',
      'padding-left': '18px',
      'padding-right': '18px',
      'border-radius': '8px',
      'border-style': 'none',
      'font-size': '15px',
      'font-weight': '600',
      cursor: 'pointer',
    },
  },
  Image: {
    label: 'Image',
    tag: 'img',
    container: false,
    icon: ImageIcon,
    defaultProps: { src: '', alt: '' },
    defaultStyle: { 'max-width': '100%', display: 'block', height: 'auto' },
  },
  Input: {
    label: 'Input',
    tag: 'input',
    container: false,
    icon: FormInput,
    defaultProps: { placeholder: 'Enter text…' },
    defaultStyle: {
      'padding-top': '10px',
      'padding-bottom': '10px',
      'padding-left': '12px',
      'padding-right': '12px',
      'border-width': '1px',
      'border-style': 'solid',
      'border-color': '#d1d5db',
      'border-radius': '8px',
      'font-size': '15px',
      width: '260px',
    },
  },
  Textarea: {
    label: 'Textarea',
    tag: 'textarea',
    container: false,
    icon: TextCursorInput,
    defaultProps: { placeholder: 'Your message…' },
    defaultStyle: {
      'padding-top': '10px',
      'padding-bottom': '10px',
      'padding-left': '12px',
      'padding-right': '12px',
      'border-width': '1px',
      'border-style': 'solid',
      'border-color': '#d1d5db',
      'border-radius': '8px',
      'font-size': '15px',
      width: '300px',
      'min-height': '96px',
    },
  },
  Divider: {
    label: 'Divider',
    tag: 'hr',
    container: false,
    icon: Minus,
    defaultStyle: { 'border-top-width': '1px', 'border-top-style': 'solid', 'border-color': '#e5e7eb', width: '100%' },
  },
  Spacer: {
    label: 'Spacer',
    tag: 'div',
    container: false,
    icon: StretchVertical,
    defaultStyle: { height: '48px' },
  },
  '3D': {
    label: '3D Object',
    tag: 'div',
    container: false,
    icon: Boxes,
    defaultProps: { shape: 'torusKnot', color: '#6366f1', autoRotate: true, metalness: 0.4, roughness: 0.35, wireframe: false },
    defaultStyle: { width: '320px', height: '280px', 'border-radius': '12px', overflow: 'hidden', 'background-color': '#0b1020' },
  },
};

/** Components offered in the insert panel (Body is implicit). */
export const COMPONENT_LIST = [
  'Section', 'Columns', 'Grid', 'Box', 'Card', 'Heading', 'Text', 'Quote', 'Link', 'Button', 'Image', 'Icon', '3D', 'Input', 'Textarea', 'Divider', 'Spacer',
];

export const isContainer = (component) => !!COMPONENTS[component]?.container;
